# compose.yaml
services:
  database:
    image: mysql:8.0.37
    container_name: "octane-app-database"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.data/database:/var/lib/mysql:rw
    ports:
      - '3308:3306'
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=octane_app
      - MYSQL_ROOT_PASSWORD=password